services:
  - type: web
    name: shams-api
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn shams_backend.wsgi:application --bind 0.0.0.0:$PORT
    postDeployCommand: python manage.py migrate
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://shams_user:OBmjcZO6gRltInd9I4t68wMy3QvVL9xg@dpg-d8h9lf5dt1ts7386p860-a/shams_db