# Generated by Django 6.0.5 on 2026-06-01 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +992XXXXXXXXX (9 цифр после кода страны)', regex='^\\+?992?\\d{9}$')], verbose_name='Номер телефона')),
                ('shams_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='SHAMS ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
