# Generated by Django 6.0.5 on 2026-06-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuan_to_tmt', models.DecimalField(decimal_places=2, default=0.65, max_digits=10, verbose_name='Курс юаня к сомони')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Комиссия платформы (%)')),
                ('shipping_price_per_kg', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='Цена доставки за 1 кг')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка курса',
                'verbose_name_plural': 'Настройки курсов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='Название товара')),
                ('product_url', models.URLField(blank=True, verbose_name='Ссылка на товар')),
                ('price_yuan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в юанях')),
                ('price_tmt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в сомони')),
                ('markup_tmt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия')),
                ('total_tmt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого к оплате')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('purchased', 'Выкуплено'), ('in_china', 'На складе в Китае'), ('in_transit', 'В пути'), ('in_dushanbe', 'Прибыло в Душанбе'), ('delivered', 'Выдано')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трек-номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.user')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
