# Generated by Django 6.0.5 on 2026-06-04 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currencyrate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.URLField(blank=True, verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, verbose_name='ID товара')),
                ('product_name', models.CharField(max_length=500, verbose_name='Название товара')),
                ('product_image', models.URLField(blank=True, verbose_name='Изображение')),
                ('price_yuan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в юанях')),
                ('price_tmt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в сомони')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.user')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
